export const db = "stack-over-flow-clone"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comment"
export const voteCollection = "votes"
export const questionAttachmentBucket = "questions-attachement"